bestofjs/bestofjs

src/components/search/sort-order.js
fix the monthly label from `last 30 months` to `last month`
I'm not sure if this should be `last 30 days`
=> sort order: fix monthly label

src/components/timeline/featured-projects.json
Babel used to be called `6to5`, not `5to6`.
Source: https://github.com/babel/babel/issues/780
=> Fix typo in old Babel name

src/pages/about-page.tsx
I noticed the links in the about page are not styled differently from the text. Now they are.
Check out the about page :)
=> Update about page links styling

package-lock.json, package.json, src/components/core/project-utils.test.ts, src/components/core/project.tsx
Generate the project slug (used in project details page URL `/projects/:slug`) by ourselves instead of relying on `slugify` NPM package.
We should allow the "$" symbol in project slugs as requested by @nin-jin here: https://github.com/michaelrambeau/bestofjs/issues/451#issuecomment-1017255754
Unit tests were added to ensure the slugs are correctly generated.
=> Generate custom project slug to allow `$` in URLs

src/components/core/icons.tsx, src/components/core/layout.tsx, src/components/project-details/github-repo-info.tsx, src/components/project-details/npm-card/index.tsx, src/stylesheets/markdown-body.css
- Fix background color applied to images included in the README.md section #127 
- Handle [Specify theme context for images in Markdown](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/) feature
This theme context feature is used by some projects like TailwindCSS: 
Right now it looks weird because we display both light theme and dark theme logos:
=> Fix image background color inside README.md sections

src/components/timeline/timeline.tsx
- Fix broken page https://bestofjs.org/timeline 
After some investigation, the reason this page is broken is the data in `src/components/timeline/featured-projects.json`, which has `angular-1` and `vuejs`. But data get from https://bestofjs-static-api.vercel.app/projects.json (`state.entities.projects`) does not have `angular-1` and `vuejs` (but have `angular`, `vuejs-2`, `vuejs-3`). Then, logic in `useTimelineProjects` make the page broken.
```js
function useTimelineProjects() {
const projects: BestOfJS.Project[] = useSelector(
findProjectsByIds(featuredProjects.map(({ slug }) => slug))
); // CONTAIN `null`
return featuredProjects.map(({ slug, date, comments }) => {
const project: BestOfJS.Project | undefined = projects.find(
(project) => project.slug === slug // CANNOT FIND slug of null …
```
=> Make sure timeline page not broken

vite.config.ts
- Remove redundant `ejs` config in `vite.config.ts`.
- I thought that config `inject.data.env` is to enject to `process.env`, but it's not correct. accessing `<% if (process.env.VERCEL_ENV === 'production') { %>` is supported by `ejs` natively.
- If I config as
```js
inject: {
data: {
env,
},
},
```
I should write in the `index.html` like this
```js
<% if (env.VERCEL_ENV === 'production') { %>
```
But I use `process.env.VERCEL_ENV`, so no need any injection.
Change 
- Build the app in PROD mode
```command
VERCEL_ENV=production npm run build
```
=> We should see the cloudflare analytics in the index.html
- Build the app in Preview mode
```command
VERCEL_ENV=preview npm run build
```
=> We should not see the cloudflare analytics in the index.html
cc: @michaelrambeau
=> Remove unused config for ejs

src/components/tags/project-tag.tsx
Fix the tag links from a page whose number is greater than 1.
E.g. https://bestofjs.org/projects?tags=component&page=2
When clicking on a tag link, the pagination should be reset.
- Go to the "component toolkit" page: https://bestofjs.org/projects?tags=component
- Go to the next page (page number 2) => https://bestofjs.org/projects?tags=component&page=2
- Click on any tag ("design system") for example: a page with no result will be displayed in production! https://bestofjs.org/projects?tags=design-system&page=2 because the page number is not reset
Before the correction:
=> Fix tag link from page N

src/index.tsx, src/root.tsx, src/stylesheets/css-reset.css
Fix a visual bug in some project README sections: some images are huge (taking all the available width, instead of a fixed width).
Examples:
- Expo project: https://bestofjs.org/projects/expo
- tRPC project: https://bestofjs.org/projects/trpc
Reason: Chakra UI comes with a Reset CSS file, whose style cause the problem.
https://github.com/chakra-ui/chakra-ui/blob/v1/packages/css-reset/src/css-reset.tsx
```css
img,
video {
max-width: 100%;
height: auto;
}
```
Rather than trying to override the styles (it was my first attempt but it's not trivial), I think it's cleaner to use our own Reset CSS file, created from Chakra UI's one.
Open the projects mentioned above and check that the logo is displayed correctly (like in the original GitHub README!)
=> Fix logos displayed as huge images in the README section of project details page

src/components/project-list/project-table.tsx
- Open a link in the GitHub link and the Project's Homepage should open a new tab instead of navigating directly
- Click on any GitHub link or Project's Homepage of `ProjectTableRow`
=> 🔗 Open new tab when clicking on Github or project's homepage

apps/bestofjs-nextjs/src/components/search-palette/search-palette.tsx
When I search for something that doesn't exist in projects and tags, I should not see the `Tags` and `Projects` headers.
1. Open the search menu
2. Search for something that doesn't exist.
3. Confirm only `''No results found.''` renders in the results area.
Error case:
Fixed:
=> fix: When no results are found, do not render useless headings

apps/bestofjs-nextjs/package.json, apps/bestofjs-nextjs/src/app/layout.tsx, pnpm-lock.yaml
It would be nice to get data about the traffic and the pages visited by users, without compromising user's privacy and without introducing heavy scripts in the client.
Now that we have more server-centric application, it should run on the server, ideally.
Let's try Vercel Analytics: https://vercel.com/docs/concepts/analytics/quickstart
Unfortunately it's not a server-side only solution:
> If everything is set up properly, you should be able to see a Fetch/XHR request in your browser's Network tab from /_vercel/insights/view when you visit any page
Related: #105
=> Try Vercel analytics for Next.js app

apps/bestofjs-nextjs/src/app/globals.css, apps/bestofjs-nextjs/src/app/page.tsx, apps/bestofjs-nextjs/src/components/core/section.tsx, apps/bestofjs-nextjs/src/components/header/desktop-nav.tsx, apps/bestofjs-nextjs/src/components/project-list/project-table.tsx, apps/bestofjs-nextjs/src/components/tags/project-tag.tsx, apps/bestofjs-nextjs/src/components/ui/badge.tsx, apps/bestofjs-nextjs/src/components/ui/card.tsx, apps/bestofjs-nextjs/tailwind.config.js
Following the great [feedback](https://github.com/bestofjs/bestofjs/issues/176#issuecomment-1668896120) we got on GitHub, it's time to spend some time improving the design of the dark mode!
- Black background instead of the blueish one
- Make cards less dark to make them more and decrease the high contrast between dark background and white text
- More visible links inside project tables (orange + mono font)
- More visible tags inside the project tables
- Decrease max page width to match the current version (`1000px`)
- Make the logo orange for consistency
- Use more the mono font for some links and titles, to get a more "high tech" touch
It's only the 1st iteration, to be continued...
=> Improve dark mode design on beta

apps/bestofjs-webui/src/global.d.ts, apps/bestofjs-webui/src/selectors/projects-selectors.ts
In the backend, a status option "featured" was added to be able to detect the projects considered as "Featured":
https://github.com/bestofjs/bestofjs-backend/commit/21ed1533e9048d3284d1a57dffcfbe9f96684a9d
Before we were only relying on the existence of a specific icon for the project, which was not great as we want the ability to setup a custom icon without making the project "Featured".
Note: there is no specific criteria to make a project "Featured" we only want highlight a subset of important projects.
There are currently 237 projects showing up, I'm cleaning up up to try to make this  number close to 200.
Related PR for the beta version: https://github.com/bestofjs/bestofjs/pull/184
=> Handle `isFeatured` flag to select "Featured projects"

apps/bestofjs-nextjs/src/app/backend.ts, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-member-list.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/loading.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/page.tsx, apps/bestofjs-nextjs/src/components/core/project-avatar.tsx, apps/bestofjs-nextjs/src/components/core/typography.tsx, apps/bestofjs-nextjs/src/components/footer/footer.tsx, apps/bestofjs-nextjs/src/components/header/desktop-nav.tsx, apps/bestofjs-nextjs/src/components/header/mobile-nav.tsx, apps/bestofjs-nextjs/src/components/home/home-featured-projects.client.tsx, apps/bestofjs-nextjs/src/config/site.ts, apps/bestofjs-nextjs/src/lib/global.d.ts, apps/bestofjs-webui/src/global.d.ts
Add missing _Hall of Fame_ page from the current version: https://bestofjs.org/hall-of-fame
I was not sure about where to put the link to the Hall of Fame: I reproduced what we do in production, adding a "More" button in the site header, to reveal more links.
Instead of this button, we could use the "Navigation Menu" component: https://ui.shadcn.com/docs/components/navigation-menu
I like the fact that you don't have to click to reveal the navigation items with this "Navigation Menu", it's triggered by a mouse `hover`, it helps to discover all the links of the application.
I added a loading state but I realized we never see it when the application is built: the page has no search parameters, so it's statically built and I think the loading state never shows up.
Click on "More" button in …
=> Add Hall of Fame page to beta version

apps/bestofjs-nextjs/src/app/about/page.tsx, apps/bestofjs-nextjs/src/app/globals.css, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-member-list.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/page.tsx, apps/bestofjs-nextjs/src/app/layout.tsx, apps/bestofjs-nextjs/src/app/page.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-github/github-card.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-npm/dependencies-section.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-npm/project-details-npm.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-header.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-readme/readme.css, apps/bestofjs-nextjs/src/app/projects/page.tsx, apps/bestofjs-nextjs/src/components/core/section.tsx, apps/bestofjs-nextjs/src/components/core/typography.tsx, apps/bestofjs-nextjs/src/components/footer/footer.tsx, apps/bestofjs-nextjs/src/components/home/featured-project-list.tsx, apps/bestofjs-nextjs/src/components/project-list/project-table.tsx, apps/bestofjs-nextjs/src/components/search-palette/search-palette.tsx, apps/bestofjs-nextjs/src/components/tags/project-tag.tsx, apps/bestofjs-nextjs/src/components/tailwind-indicator.tsx, apps/bestofjs-nextjs/src/components/ui/button.tsx, apps/bestofjs-nextjs/src/lib/fonts.ts, apps/bestofjs-nextjs/tailwind.config.js
Following the feedback about fonts #176 this PR introduces the same serif font we use in production (`Roboto_Slab`) for headings and paragraphs.
The mono font (`JetBrains_Mono`) is removed.
The `OpenSans` font is used for interactive elements: menus, links, buttons...
Extra fix: when removing a tag from the search results page, the current text filter should not be reset.
- Search for `sindre`
- Add a tag from the list of tag used to refine the search
- Removing the tag or the search filter by pushing the X button should not reset the whole search state
=> Use a serif font in Beta version

apps/bestofjs-nextjs/src/app/api/revalidate/route.ts, apps/bestofjs-nextjs/src/app/not-found.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/get-project-details.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-npm/monthly-downloads-charts.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-readme/project-readme.tsx, apps/bestofjs-nextjs/src/app/rankings/monthly/monthly-rankings-data.ts
We have an issue related to caching on beta.bestofjs.org: page details (`/projects/:id`) show stale data instead of the latest data.
It's obvious on this screenshot: the data for July is missing, in the graph:
The reason: the page is cached after the first visit and because it has no search parameters, and it's never re-validated.
https://nextjs.org/docs/app/building-your-application/caching
This PR fixes the problem by forcing the page to be re-validated every 24 hours and by providing an end-point to purge the cache on-demand.
https://nextjs.org/docs/app/api-reference/functions/revalidateTag#parameters
TODO in the backend: call this end-point when the static API (the big JSON file consumed) is re-built, every day.
This PR also adds `not-found` page to avoid showing the Vercel's default …
=> Add revalidate API end-point

apps/bestofjs-nextjs/src/app/page.tsx, apps/bestofjs-nextjs/src/app/search-container.tsx, apps/bestofjs-nextjs/src/components/header/desktop-nav.tsx, apps/bestofjs-nextjs/src/components/header/mobile-nav.tsx, apps/bestofjs-nextjs/src/components/header/site-header.tsx, apps/bestofjs-nextjs/src/components/home/home-featured-projects.client.tsx, apps/bestofjs-nextjs/src/components/icons.tsx, apps/bestofjs-nextjs/src/components/search-palette/search-palette.tsx, apps/bestofjs-nextjs/src/components/search-palette/search-trigger.tsx, apps/bestofjs-nextjs/src/components/ui/command.tsx
Improve UX on mobile, following the feedback we got here https://github.com/bestofjs/bestofjs/issues/176#issuecomment-1685607435
- show _Best of JS_ logo
- replace the input field that triggers the search palette with a search icon
- hide Discord and GitHub icons (moved to the navigation menu for mobiles)
- make "Featured Projects" block take all the available space instead of the hard-coded 300px
- make the search palette take the whole height
On small screens, the top bar is now made of the following elements:
- The menu button that reveals a meeny sliding from the left
- The _Best of JS logo_
- The search icon
- The dark/light mode switcher
=> Improve UX on small screens for the beta version

apps/bestofjs-nextjs/src/components/project-list/project-table.tsx
I noticed in the [previous PR](https://github.com/bestofjs/bestofjs/pull/193), projects cards with many tags tend to get squished in mobile.
This PR moves the github-stars area to the top on mobile to free up more space.
By screen size **( Original | PR fixed )**
XS:
SM:
MD:
LG:
=> Improve UX on small screens for the beta version 

apps/bestofjs-nextjs/src/app/backend.ts, apps/bestofjs-nextjs/src/app/projects/error.tsx, apps/bestofjs-nextjs/src/components/core/project-avatar.tsx
In an attempt to avoid fetching too many times the JSON data used server-side, a caching mechanism was implemented to hold the data "in memory".
It seems to lead to inconsistencies when using https://beta.bestofjs.org/: 
- on the top page we can see new projects added recently (so the top page has been re-built with the latest data, as expected)
- clicking on one of the links to see the details of new project (Example: `https://beta.bestofjs.org/projects/typedi` leads to a page showing "Project not found", which happens when a given project is not found in the JSON data.
This PR removes this caching mechanism as Next.js already provides its own mechanism: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-f …
=> Fix errors related to caching in Beta

apps/bestofjs-nextjs/src/components/search-palette/search-trigger.tsx, apps/bestofjs-nextjs/src/components/search-palette/use-is-apple-platform.ts
Show `Ctrl K` on non apple platforms, and `⌘ K` on Apple platforms.
I tested on Linux. Maybe @michaelrambeau you can test on MacOS? :grin:
=> Show Ctrl K on non apple platforms

README.md, apps/bestofjs-nextjs/next.config.mjs, apps/bestofjs-nextjs/src/app/api/og/projects/[slug]/route.tsx, apps/bestofjs-nextjs/src/components/search-palette/search-trigger.tsx
- Update README after the release of the Next.js version and the creation of the URL `classic.bestofjs.org`
- Add redirect from `/tags/:tag` to `/projects?tags=:tag` to take into account some links in the README (I think it would be nice to have URLs `/tags/:tag` in the future, we could generate the page statically because of the absence of query string parameters)
- Improve OG image layout for project details, it was not good when the description was long (E.g. `Epic Stack` project), the logo is now aligned to the top
=> Improve OG image for projects's pages

apps/bestofjs-nextjs/.eslintrc.cjs, apps/bestofjs-nextjs/src/app/api/featured-projects/route.ts, apps/bestofjs-nextjs/src/app/api/og/projects/[slug]/route.tsx, apps/bestofjs-nextjs/src/app/api/og/route.tsx, apps/bestofjs-nextjs/src/app/api/search-data/route.ts, apps/bestofjs-nextjs/src/server/api-local-json.ts, apps/bestofjs-nextjs/src/server/api-remote-json.ts, apps/bestofjs-nextjs/src/server/api-utils.tsx, apps/bestofjs-nextjs/src/server/api.ts, apps/bestofjs-nextjs/src/server/create-api.tsx
Fix local build and re-introduce the local JSON file used as a local cache and re-built every day.
Because we have edge functions that generate images dynamically and that can access the file system, there are 2 versions of the API layer:
- one that uses the local JSON data `import {api} from "@app/server/api"` (the default one used for all pages) 
- one that uses that fetches JSON data remotely `import {api} from "@app/server/api-remote-json"`, used by API end-points with the `edge` runtime
The gist: the function that creates the `api` object used to query data now accepts a `fetchProjectData` function.
The strategy to fetch data (using local or remote JSOB) is considered as a dependency.
```ts
function createAPI(fetchProjectData: () => Promise<RawData>) {
const { projects, tags, date } …
```
=> Fix local build using a local JSON file for data

README.md, apps/bestofjs-nextjs/README.md, apps/bestofjs-nextjs/src/app/layout.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx, apps/bestofjs-nextjs/src/app/projects/loading.tsx, apps/bestofjs-nextjs/src/server/api-utils.tsx, apps/bestofjs-webui/src/components/home/beta-version-news.tsx
In production, absolute URLs used to link the OG image in the page `<head>` should start with `https://bestofjs.org` instead of the Vercel URL (E.g. `https://bestofjs-kzvsa011l-bestofjs.vercel.app/api/og"`)
It might be the cause of OG images showing "Project not found" for projects added recently to _Best of JS_.
Also: fixes the number of projects displayed about the tag name, in several places, including the "Popular Tags" section in the home page.
Check the page code source.
```html
<meta property="og:image" content="http://localhost:3000/api/og"/>
```
https://bestofjs-nextjs-git-fix-metadata-bestofjs.vercel.app/
```html
<meta property="og:image" content="https://bestofjs-nextjs-gc5avwdbx-bestofjs.vercel.app/api/og"/
```
The image I'd like to fix:
Probable cause: Next.js looks up a …
=> Fix pages metadata URLs and tags number of projects

apps/bestofjs-nextjs/README.md, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-npm/dependencies-section.tsx, apps/bestofjs-nextjs/src/components/ui/card.tsx
Fix the layout of the dependencies table, removing table headers "Dependencies on Best of JS" and "Dependencies not on Best of JS".
The layout is currently broken on production:
I think it looks better without header at all? (screenshot below)
Check projects that have a related NPM package, with different scenarios.
Only deps that are NOT on Best of JS:
http://localhost:3000/projects/axios
A mix of projects on and not on Best of JS: 
- http://localhost:3000/projects/tldraw
- http://localhost:3000/projects/genql
=> Simplify NPM dependencies layout

apps/bestofjs-nextjs/src/app/featured/loading.tsx, apps/bestofjs-nextjs/src/app/featured/page.tsx, apps/bestofjs-nextjs/src/components/project-list/navigation-state.tsx
Fix an issue related to the "Featured projects" page (`/featured`) pagination in production.
When you go to `/featured` and then click on the next button (which has the effect of adding a query string:`/featured?page=2`), it does not not work, nothing happens.
Oddly the problem cannot be reproduced in local when building for production (`build` and `start` commands) 🙀 
If I manually add the query string `?page=1` and load the URL, the next button works.
This problem does not happens with other paginated pages like `/pages` and `/tags`.
After several tests (the different commits of this PR), the difference is that there is no `loading.tsx` page, for the loading state. Adding `loading.tsx` seems to fix the problem... it's very weird, I can't understand the reason.
- Check the Preview link …
=> Fix "Featured Projects" pagination

apps/bestofjs-nextjs/src/app/projects/[slug]/project-readme/project-readme.tsx, apps/bestofjs-nextjs/src/lib/global.d.ts
Fix missing images the README section of the project details page.
E.g. https://bestofjs.org/projects/guide-to-fp
Reason: a branch name is not passed to the API end-point that fetches the README
The branch name is needed to create the URLs for local images included in the README, currently we pass `undefined` as a string instead of the default branch name: `https://raw.githubusercontent.com/MostlyAdequate/mostly-adequate-guide/undefined/images/cover.png`
Note: the JSON data only include the default branch name if it's different than `master`, otherwise the the `branch` field is missing, this is why I adjusted the type to make it optional.
Ensure the image shows up correctly when going to `/projects/guide-to-fp`
After, the book cover shows up :)
=> Ensure a branch name is set when fetching README from API

apps/bestofjs-nextjs/next.config.mjs, apps/bestofjs-nextjs/src/app/api/og/hall-of-fame/route.tsx, apps/bestofjs-nextjs/src/app/api/og/og-image-layout.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/actions.ts, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-fame-search.client.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-fame-view.client.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/loading.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/page.tsx, apps/bestofjs-nextjs/src/components/ui/input.tsx, apps/bestofjs-nextjs/src/server/api-hall-of-fame.tsx
Improve the JavaScript Hall of Fame feature (`/hall-of-fame`):
- add a basic search form using Server actions, to filter the member by name and GitHub username
- show more projects related to Hall of Fame members by looking up projects from JSON projects data, adding projects whose "owner" is the Hall of Fame member
The `Input` component from https://ui.shadcn.com/docs/components/input was added.
About the implementation, this first iteration is very basic:
- No URL update (meaning it's not possible to share or to bookmark results)
- Even if the search happens on the server side, the search is triggered by JS running on the client, it could be improved by using `<form action={myServerAction}>` and `FormData` to read parameters
- Go to the Hall of Fame page (you have to click to the "More" …
=> Add Hall of Fame basic search feature

apps/bestofjs-nextjs/src/app/api/revalidate/route.ts, apps/bestofjs-nextjs/src/app/hall-of-fame/actions.ts, apps/bestofjs-nextjs/src/server/api-hall-of-fame.tsx
- Make Hall of Fame search feature (introduced here #222) faster by removing the `sleep` function used during testing 😅 
- Add `/api/revalidate?path=/hall-of-fame` API route to be able to re-build the Hall of Fame page
- Go to the Hall of Fame page (you have to click to the "More" button from the top page)
- By default, all members are displayed (+140 members, no pagination for now!)
- Enter something like `"theo"`
- Search results should be displayed quickly, this time!
=> Fix slow Hall of Fame search

apps/bestofjs-nextjs/next.config.mjs, apps/bestofjs-nextjs/scripts/build-project-data.mjs, apps/bestofjs-nextjs/src/app/rankings/monthly/route.tsx
Fix a 404 error showing up in the console, about React Server Components for `/rankings/monthly` path:
```        
GET https://bestofjs.org/rankings/monthly?_rsc=acgkz 404 (Not Found)
```
This path, used for the "Monthly" link in the menu, redirects the user to the latest month rankings page (E.g. `/rankings/monthly/2023/9`).
The redirect was setup using a API route (`route.tsx`).
Now it's setup using the main Next.js config file (which is a `.mjs` file, not TypeScript).
- Ensure the error is gone
- Ensure the redirect works as expected: click on "Monthly" in the top bar
=> Fix 404 error in the console because of redirect

.github/workflows/pull-request-check.yml
Ensure e2e runs on the `nextjs` version of our vercel deployment.
Needed to specify the correct `environment:` in the plugin.
Github's environment names use a special ASCII dash
> example: "Preview – bestofjs"
You need to confirm the name as returned from the API
```
curl -L \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer API_AUTH_TOKEN" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/bestofjs/bestofjs/deployments
```
When bestofjs-classic vercel builds and deploys first, our e2e test will not run.
You can confirm by the timestamps on this PR's run
by checking `bestofjs-classic` was ready first, and the e2e tests waited until the correct environment was up.
1. Classic was deployed first.
2. E2E test waited for the correct version of the app to …
=> fix(e2e:ci): make sure we target the bestofjs-nextjs

apps/bestofjs-nextjs/src/app/layout.tsx
Fix caching issue about the OG image generated when sharing Best of JS link on social networks.
I noticed the problem when creating a post on LinkedIn that includes the link https://bestofjs.org/ and from several autonatic messages on Slack
The image was including data about the hottest projects a few days ago, not today.
You can see the problem when using a HTTP client like `Bruno` and making a request to https://bestofjs.org/api/og
Adding the timestamp to the URL solves the issue.
=> Add timestamp to OG image URL to fix caching issue

apps/bestofjs-nextjs/src/app/api/og/og-utils.tsx, apps/bestofjs-nextjs/src/app/api/og/projects/[slug]/route.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/page.tsx, apps/bestofjs-nextjs/src/app/layout.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx, apps/bestofjs-nextjs/src/config/site.ts
Fix the OG image not showing up when posting on Twitter.
Everything works finw on Slack, Discord and any OG data viewer I have checked, including Twitter card preview... but not on Twitter itself.
It seems the reason is the absence of `og:url` metadata.
So this PR add meta data for the 3 pages that have an OG image:
- home page
- project details page
- hall of fame
- Go to Twitter (or X depending on how you call it!
- Create a tweet including a URL from Best of JS
- The draft should include the card after a few seconds
=> Fix OG image not showing up on Twitter

apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-fame-search.client.tsx, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-member-list.tsx, apps/bestofjs-nextjs/src/app/page.tsx, apps/bestofjs-nextjs/src/components/core/section.tsx, apps/bestofjs-nextjs/src/server/api-projects.tsx
- Fix incorrect total number of projects displayed in the "Do you want more projects?" section of the home page, adding a new API method `api.projects.getStats()`
- Load Hall of Fame members lazily (about 150 images are included in the page as we show ALL members by default)
Check the "Do you want more projects?" at the bottom of the top page: the number of projects should match what you see when visiting the "All Projects" page (`/projects`)
=> Fix total number of projects in home page

apps/bestofjs-nextjs/src/app/projects/page.tsx
Add missing metadata in the projects list pages (`/projects?...` path), taking into account different scenarios (with or without tags, with or without text query)
- Custom description
- Custom title
- Add missing OG URL to get the OG image working in Twitter (see #230 )
It should improve the content of the cards when sharing links on social networks and it could improve the SEO too.
- Go to the Projects page 
- Trigger different searches
- Check page meta data from the DevTools, inspecting the page `<head>`.
- title = `All projects`
- description = `All the 1940 projects tracked by Best of JS: freeCodeCamp, React, Vue.js 2, JS Algorithms & Data Structures, You Don't Know JS, Bootstrap, VS Code, Airbnb Style Guide, 30 seconds of code, Next.js...`
- title = `Node.js framework`
- description …
=> Improve `/projects` pages metadata

apps/bestofjs-nextjs/src/app/api/og/hall-of-fame/route.tsx, apps/bestofjs-nextjs/src/app/api/og/og-image-layout.tsx, apps/bestofjs-nextjs/src/app/api/og/og-utils.tsx, apps/bestofjs-nextjs/src/app/api/og/projects/[slug]/route.tsx, apps/bestofjs-nextjs/src/app/api/og/projects/route.tsx, apps/bestofjs-nextjs/src/app/api/og/route.tsx, apps/bestofjs-nextjs/src/app/api/stats/route.ts, apps/bestofjs-nextjs/src/app/featured/page.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx, apps/bestofjs-nextjs/src/app/projects/page.tsx, apps/bestofjs-nextjs/src/components/project-list/sort-order-options.ts
- Improve the OG image for the `/projects` paths (introduced by #215 ) by showing the current sort option
- Show tag display name instead of the tag code
- Add the current sort to page metadata, so that it shows up in the text displayed with the image on social networks
- Refactoring to remove duplicate code (`getSortOption` => `getSortOptionByKey`, moved to the file about `SortOption` definition)
- Improve the layout making the `Best of JS` logo less big, giving more space to the real content (since the vertical space is very limited!)
Check the image generated at `/api/og/projects?tags=component&tags=react&sort=yearly`:
- it should include the current sort "By stars added the 12 last months"
- the right column of the table should show the number of stars added over the 12 last months, …
=> Improve OG image of project list pages

apps/bestofjs-nextjs/src/app/api/og/projects/[slug]/route.tsx, apps/bestofjs-nextjs/src/app/layout.tsx, apps/bestofjs-nextjs/src/app/page.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-header.tsx, apps/bestofjs-nextjs/src/app/projects/page.tsx, apps/bestofjs-nextjs/src/helpers/url.ts, apps/bestofjs-nextjs/src/server/api-projects.tsx
OG images for project list pages are supposed to reflect the exact content of the web page (see #233 ).
However I noticed some caching issues when using the current "cache busting" technique that adds a date parameter to the image URL.
In the OG image, I got the data from the previous day instead of the fresh data I expected (screenshots below)
Instead of only adding the current date (`2023-10-29`) I think it would work better if we update the URL with a parameter that includes the date and the time when JSON was generated: `/api/og/?t=2023-10-29T21-19` E.g.
Another change related to OG image: instead of making the home page's OG image the default OG image for all pages of the app, we assign the image only for the home page, using `page.tsx` instead of `layout.tsx`.
Share URLs such as …
=> Improve cache busting technique for OG images to avoid caching issues

apps/bestofjs-nextjs/src/app/api/og/hall-of-fame/route.tsx, apps/bestofjs-nextjs/src/app/api/og/og-image-layout.tsx, apps/bestofjs-nextjs/src/app/api/og/og-utils.tsx, apps/bestofjs-nextjs/src/app/api/og/projects/[slug]/route.tsx, apps/bestofjs-nextjs/src/app/api/og/projects/route.tsx, apps/bestofjs-nextjs/src/app/api/og/route.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx
Improve the layout of OG images
- Add a gradient for the background 
- Adjust spacing
- For project's details page, show project inside a card, adjust font size depending on the length of the project's name
Check the different OG images:
- home page: `/api/og/`
- tag search: `/api/og/projects?sort=daily&tags=component&tags=react`
- list of all projects: `/api/og/projects`
- project's page: `/api/og/projects/react`
- hall of fame: `/api/og/hall-of-fame`
=> Improve OG images layout

apps/bestofjs-nextjs/src/components/project-list/project-table.tsx
Following the change made here #238 to truncate the description of the projects with CSS, the table is wider than its container and it breaks the layout!
So we need `max-width: 0` actually 😅 
Ensure everything is aligned properly in the top page!
=> Fix broken layout because of truncated text

apps/bestofjs-nextjs/src/app/robots.ts, apps/bestofjs-nextjs/src/app/sitemap.ts
Fix #241 adding sitemap and robots file to improve the SEO
`&` escape characters must be escaped: https://www.sitemaps.org/protocol.html#escaping
Docs:
- sitemap.ts: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/sitemap
- robots.ts: https://nextjs.org/docs/app/api-reference/file-conventions/metadata/robots#generate-a-robots-file
Ensure both files are generated correctly.
XML generated at https://bestofjs-git-sitemap-bestofjs.vercel.app/sitemap.xml:
```xml
<urlset>
<url>
<loc>https://bestofjs.org</loc>
<lastmod>2023-11-03T04:22:53.160Z</lastmod>
<changefreq>daily</changefreq>
<priority>1</priority>
</url>
<url>
<loc>https://bestofjs.org/hall-of-fame</loc>
<lastmod>2023-11-03T04:22:53.160Z</lastmod>
<changefreq>monthly</changefreq>
<priority>0.9</priority>
</url>
<url> …
```
=> Add sitemap and robots file to improve SEO

apps/bestofjs-nextjs/package.json, pnpm-lock.yaml
Fix warning message when running the lint command:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.2.0
YOUR TYPESCRIPT VERSION: 5.2.2
Please only submit bug reports when using the officially supported version.
```
Run `pnpm -F bestofjs-nextjs lint` and ensure there is no warning message
=> Upgrade `@typescript-eslint/parser` to latest

apps/bestofjs-nextjs/src/app/globals.css, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-member-list.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-readme/readme.css, apps/bestofjs-nextjs/src/app/projects/page.tsx, apps/bestofjs-nextjs/src/components/header/mobile-nav.tsx, apps/bestofjs-nextjs/src/components/ui/alert.tsx, apps/bestofjs-nextjs/src/components/ui/badge.tsx, apps/bestofjs-nextjs/src/components/ui/button.tsx, apps/bestofjs-nextjs/src/components/ui/dialog.tsx, apps/bestofjs-nextjs/src/components/ui/link.tsx, apps/bestofjs-nextjs/src/components/ui/sheet.tsx, apps/bestofjs-nextjs/tailwind.config.js
Cleanup following the introduction of Radix Colors tokens #250 , taking into account the comment from @flamrdevs as there was a miss about the `:hover` color effect of some buttons.
- The 2 variants `primary` use  `secondary` use tokens from the `orange` and the `sand` scales respectively
- The `destructive` variant was removed
Also new CSS variables are introduced for links:
- `link-foreground`
- `link-underline`
- Go to the Hall of Fame `/hall-of-fame`
- Check the `:hover`effect of the Search button, in both light and dark mode
=> Cleanup CSS variables, add missing `:hover` effect

apps/bestofjs-nextjs/package.json, apps/bestofjs-nextjs/src/app/layout.tsx, apps/bestofjs-nextjs/src/components/tag-list/tag-list.tsx, apps/bestofjs-nextjs/src/components/ui/link.tsx, apps/bestofjs-nextjs/src/components/ui/tooltip.tsx, apps/bestofjs-nextjs/src/server/api-utils.tsx, pnpm-lock.yaml
Add tag's description in the tags list page.
This is the commit that made the description available in the static API (the huge JSON file queried by the Next.js app, in the server-side): https://github.com/bestofjs/bestofjs-backend/commit/06e6c856ee50555f4a9aec5c1e167b561e4827ae
Note: not all tags have a description.
In addition: a tooltip is added on project's icons, to show the project's  name
- Go to `/tags` page 
- Check a description is displayed
- Mouse `:hover` the project's icons: a tooltip with the project name should be displayed.
=> Add tag description in tag list page

apps/bestofjs-nextjs/next.config.mjs, apps/bestofjs-nextjs/package.json, apps/bestofjs-nextjs/src/app/projects/[slug]/project-readme/project-readme.tsx, pnpm-lock.yaml
Fix #260 images don't show in the README section.
Reason: GitHub API converts image absolute URLs into specific URLs on the domain `private-user-images.githubusercontent.com` that have a short time to live (about 5 minutes, according to my tests).
After this delay, the URL does not display anything.
~~So we need to revalidate the cache related to README request every 5 minutes because of images from `private-user-images.githubusercontent.com`~~
Re-validating after N minutes is not enough because the first person who would trigger a re-render of the page after the image validity expired would get a broken image, another browser reload is needed to get the updated README content on the screen.
So it seems we need to disable any caching when fetching README content, using `{cache: …
=> Fix broken images in README section and enable PPR

apps/bestofjs-nextjs/src/app/api/og/og-utils.tsx, apps/bestofjs-nextjs/src/app/globals.css, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-member-list.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-header.tsx, apps/bestofjs-nextjs/src/components/core/index.tsx, apps/bestofjs-nextjs/src/components/core/project-avatar.tsx, apps/bestofjs-nextjs/src/components/core/project-logo.tsx, apps/bestofjs-nextjs/src/components/core/project-utils.ts, apps/bestofjs-nextjs/src/components/home/featured-project-list.tsx, apps/bestofjs-nextjs/src/components/project-list/project-table.tsx, apps/bestofjs-nextjs/src/components/search-palette/search-palette-results.tsx, apps/bestofjs-nextjs/src/components/search-palette/search-palette.tsx, apps/bestofjs-nextjs/src/components/tag-list/tag-list.tsx, apps/bestofjs-nextjs/src/components/tags/project-tag-hover-card.tsx
Cleanup `ProjectLogo` component
- ensure the logo is always displayed as a square, overriding `height: auto` coming from Tailwind CSS (I noticed the problem after Astro logo was updated by this PR #263 )
- remove classes that have no effect
- Rename `ProjectAvatar` => `ProjectLogo`
About TailwindCSS reset: https://tailwindcss.com/docs/preflight
Check the logo for projects that have a custom SVG file whose `viewPort` is not a square 
Examples:
- Astro
- Nuxt
=> Cleanup project logo component

apps/bestofjs-nextjs/playwright.config.ts, apps/bestofjs-nextjs/tsconfig.json
Restore the E2E test suite that I had to disable 2 weeks ago, when the build was broken on Vercel.
I'm not too sure what happened at the time, there was no change from our side but one day the project was not building anymore: 
the error was a TypeScript error because of `playwright.config.ts` file, the package `@playwright/test` was not found (which is normal since we run in production mode on Vercel, devDependencies are not installed as we want the test suite to run on GitHub actions only)
So this PR restores the test suite by:
- restoring the config file
- ensure the TS compiler only compiles files from the `src` folder (maybe I should exclude `playwright.config.ts` instead?)
Ensure all the checks pass on GitHub actions!
=> Restore end-to-end test suite with Playwright

apps/bestofjs-nextjs/src/components/search-palette/search-palette-state.ts
Fix the bug about the search palette mentioned here: https://github.com/michaelrambeau/bestofjs/issues/938
Cause: the page parameter should be reset when opening a tag from the search palette.
Note: we try to keep the search parameters to maintain the search order picked by the user (E.g. "by number of stars")
- Go to "All projects" page
- Scroll and go to the next page to open http://localhost:3000/projects?sort=total&page=2
- Press Cmd K to Open the search palette
- Search for a tag, select it, and check the tag page open correctly
=> Fix open a tag from the search palette when the current page is > 1

apps/bestofjs-nextjs/src/components/theme-toggle.tsx
The `theme` field returned by the `useTheme` hook of [next-themes](https://github.com/pacocoursey/next-themes?tab=readme-ov-file#usetheme-1) has the literal value `system` if it has not been manually modified.
So if the user has `light` as the system preference, on the first click the handler 
```ts
onClick={() => setTheme(theme === "light" ? "dark" : "light")}
```
will set the theme to `light` again, since `"system" !== "light"`.
Go to https://bestofjs.org/ from an incognito tab with system preference set as light and click the theme toggle icon. On the first click the theme will not change.
=> Fix theme toggle

.github/workflows/update-github-data.yml, apps/backend/src/cli.ts, apps/backend/src/iteration-helpers/process-projects.ts, apps/backend/src/iteration-helpers/process-repos.ts, apps/backend/src/task-runner.ts
Add a `concurrency` parameter to the backend apps to speed up the daily build process on GitHub actions.
The goal is to be able to run the task `update-github-data` in a reasonable time (less than 30 minutes)
Use the dummy task `hello-world` to check the effect of the concurrency.
```sh
bun run apps/backend/src/cli.ts hello-world --limit 100 --logLevel 4 --concurrency 10 
```
=> Feat(backend) Add `concurrency` parameter for DB scripts

.github/workflows/update-github-data.yml, apps/backend/.gitignore, apps/backend/package.json, apps/backend/src/cli.ts, apps/backend/src/iteration-helpers/process-projects.ts, apps/backend/src/iteration-helpers/process-repos.ts, apps/backend/src/iteration-helpers/utils.ts, apps/backend/src/task-runner.ts, apps/backend/src/tasks/build-static-api.task.ts, apps/backend/vercel.json, packages/db/src/github/github-api-client.ts, packages/db/src/projects/tags.ts, pnpm-lock.yaml
- Fix TS errors in `backend` app
- Fix deploy of `build-static-api` on Vercel, allowing deploys when commits are pushed
- Add `throttleInterval` parameter to `update-github-data` to avoid hitting rate limit from GitHub API
From the GitHub API docs https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28, there is a limit of 5000 requests by hours (720 ms between requests)
The throttling is done with [p-throttle](https://github.com/sindresorhus/p-throttle) package.
No errors when launching this command
```sh
p -F backend typecheck:watch  
```
To check the effect of concurrency, the following script, with an interval of 1 second, should take one minute
```
bun run apps/backend/src/cli.ts hello-world --limit 60  --concurrency 1 --throttle-interval …
```
=> Migration backend / Fix TS errors, fix static API build on Vercel

.github/workflows/update-github-data.yml, apps/backend/package.json, apps/backend/src/cli.ts, apps/backend/src/flags.ts, apps/backend/src/task-runner.ts, apps/backend/src/tasks/build-static-api.task.ts, apps/backend/src/tasks/hello-world.task.ts, apps/backend/src/tasks/trigger-build-static-api.ts, apps/backend/src/tasks/update-github-data.task.ts
We need to orchestrate the flow between the 2 daily tasks:
- step 1: `update-github-data` runs on GitHub actions
- step 2: `build-static-api` runs on Vercel 
The solution is to send a webhook from GitHub action, after `update-github-data` script completed, to trigger the build on Vercel.
This PR introduces a new task called `trigger-build-static-api` that pings the webhook URL setup in Vercel.
Other changes:
- refactor the CLI tasks to avoid too much boilerplate
- share env variables between all steps in the GitHub action pipeline
To send the webhook:
```
bun run apps/backend/src/cli.ts trigger-build-static-api 
```
- Do not trigger the webhook if the `update-github-data` script fails (trigger an exit code different than 0 under some conditions to define)
- Instead of a separate step, we …
=> Backend trigger static api build

.github/workflows/update-package-data.yml, apps/backend/package.json, apps/backend/src/apis/npm-api-client.ts, apps/backend/src/cli.ts, apps/backend/src/iteration-helpers/process-projects.ts, apps/backend/src/tasks/build-static-api.task.ts, apps/backend/src/tasks/update-package-data.task.ts, packages/db/tsconfig.json, pnpm-lock.yaml
Add the task to update package data (`packages` table in the new database)
For each package, we store the following data:
- version number
- dependencies
- deprecated
- monthly downloads
To be run everyday.
To run the script locally on a limited amount of projects
```sh
bun run apps/backend/src/cli.ts update-package-data  --limit 10
```
=> Migration backend / add `update-package-task`

apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-github/github-card.tsx
- The goal of this PR is to add a forward slash (/) to the end of the GitHub project link in the README file.
- Check out the branch with this PR.
- Start nextjs app
- Navigate to 'projects page'. e.v `/projects/nodejs`
- Click on github repository external link
=> Fix(external-link): add / to github project link

apps/backend/package.json, apps/backend/src/cli.ts, apps/backend/src/flags.ts, apps/backend/src/task-runner.ts, apps/backend/src/tasks/build-static-api.task.ts, apps/backend/src/tasks/notify-daily.task.ts, apps/backend/src/tasks/static-api-types.ts, apps/backend/src/tasks/trigger-build-webapp.task.ts, apps/backend/vercel.json, pnpm-lock.yaml
Add `static-api-daily` script to be run by build process on Vercel.
Build command setup on Vercel: `pnpm -F backend static-api-daily`
This script is made of 3 tasks:
- `build-static-api` (the main one) rebuilds the JSON file with consolidated data consumed by the app
- `trigger-build-webapp` sends the webhook to revuild Next.js app
- `notify-daily` sends daily notifications on Slack and Discord
=> Backend: Trigger Next.js rebuild after static API is generated

.gitignore, apps/admin/src/app/projects/[slug]/actions.ts, apps/admin/src/app/projects/[slug]/edit/page.tsx, apps/admin/src/app/projects/[slug]/page.tsx, apps/admin/src/app/projects/[slug]/view-repo.tsx, apps/admin/src/db.ts, apps/bestofjs-nextjs/src/app/db.ts, apps/bestofjs-nextjs/src/app/projects/[slug]/page.tsx, packages/db/package.json, packages/db/src/database.ts, packages/db/src/index.ts, packages/db/src/local-database.ts, packages/db/src/migrate.ts, packages/db/src/projects/create.ts, packages/db/src/projects/get.ts, packages/db/src/vercel-database.ts, pnpm-lock.yaml
The Postgres database on Vercel (Fron https://neon.tech under the hood) is not the usual Postgres database: of course it's compatible with the usual drivers (`pg` package) but you have to use [@vercel/postgres package](https://www.npmjs.com/package/@vercel/postgres) to make the best of the database, this driver is powered by web-sockets, it should make requests faster.
This PR includes some refactoring to try to decrease the number of connections to the database.
Running the following request can return up to 400 rows, depending on the time of the day:
```sql
SELECT * FROM pg_stat_activity ORDER BY backend_start DESC
```
The only downside: it seems there is no solution to run easily a Vercel database locally.
So this PR introduces a "dual" set up to be able to connect to:
- either the …
=> Connect to database using `@vercel/postgres` package

.github/workflows/update-bundle-size.yml, .github/workflows/update-github-data.yml, apps/admin/src/app/projects/[slug]/actions.ts, apps/admin/src/app/projects/[slug]/edit/project-form.tsx, apps/admin/src/app/projects/[slug]/view-project.tsx, apps/backend/package.json, apps/backend/src/apis/npm-api-client.ts, apps/backend/src/cli.ts, apps/backend/src/tasks/update-bundle-size.task.ts, packages/db/drizzle/0001_light_cerise.sql, packages/db/drizzle/meta/0001_snapshot.json, packages/db/drizzle/meta/_journal.json, packages/db/src/index.ts, packages/db/src/projects/get.ts, packages/db/src/schema.ts, pnpm-lock.yaml
Following the migration to the new backend and Posgres database, this PR adds the missing task to update bundle size data stored in the `bundles` table.
Data comes from https://bundlejs.com/
Example of end-point: https://deno.bundlejs.com/?q=redux
```json
{
"query": "?q=redux",
"rawQuery": "%3Fq%3Dredux",
"version": "redux@5.0.1",
"modules": [
[
"redux@5.0.1",
"export"
]
],
"config": {
"entryPoints": [
"/index.ts"
],
"cdn": "https://unpkg.com",
"polyfill": false,
"esbuild": {
"color": true,
"globalName": "BundledCode",
"logLevel": "info",
"sourcemap": false,
"target": [
"esnext"
],
"format": "esm",
"bundle": true,
"minify": true,
"treeShaking": true,
"platform": "browser",
"jsx": "transform"
},
"ansi": "ansi",
"compression": {
"type": "gzip",
"quality": 9
}
},
"input": "// Click Build for …
```
=> Add task to update package bundle size

apps/backend/package.json, apps/backend/src/tasks/build-static-api.task.ts, apps/backend/src/tasks/notify-daily.task.ts, apps/bestofjs-nextjs/src/app/backend-search-requests.tsx, pnpm-lock.yaml
Following discussions we had with @BBlackwo we'd like to promote some projects that don't match the usual criteria and we have created a new tag called "Editor's pick" whose defintion could be:
> Projects that don't match the usual criteria about being either written in a language that compile to JavaScript or a build tool that emits JavaScript, picked by Best of JS authors.
The discussion started with the request to add the 2 following projects:
- Coolify: https://github.com/michaelrambeau/bestofjs/issues/964
- Immich: https://github.com/michaelrambeau/bestofjs/issues/980
However we don't want these projects to show up in the home page "Today's hot projects" because they tend to be the hottest projects every day.
So we want to exclude them from the rankings (daily, monthly, and yearly in …
=> Exclude specific projects from rankings

apps/backend/src/cli.ts, apps/backend/src/flags.ts, apps/backend/src/task-runner.ts, apps/backend/src/task-types.ts, apps/backend/src/tasks/build-monthly-rankings.ts, apps/backend/src/tasks/notify-daily.task.ts, apps/bestofjs-nextjs/src/app/backend-search-requests.tsx, packages/db/package.json, packages/db/src/constants.ts, packages/db/src/projects/project-helpers.ts
- As part of the migration to the new backend powered by the Postgres database, add the task to generate the monthly rankings hosted on https://github.com/bestofjs/bestofjs-rankings
- Refactor the `TaskRunner` used to run scripts, adding CLI flags that can be used for specific tasks. For example the new tasks `build-monthly-rankings` accepts 2 specific flags: `--year` and `--month`
- Refactor (DRY) setup excluded tags from rankings in one place (handing TODO from https://github.com/bestofjs/bestofjs/pull/305)
TODO: there is redundant code to write to specify the new extra flags as we use a Zod schema to validation, in addition of adding flags definition to the CLI script (built on top of https://github.com/privatenumber/cleye)
```ts
const schema = z.object({ year: z.number(), month: …
```
=> Migrate build monthly rankings task

apps/admin/src/app/projects/[slug]/edit/add-package-button.tsx, apps/admin/src/app/projects/[slug]/page.tsx, apps/admin/src/app/projects/[slug]/view-related-projects.tsx, apps/admin/src/app/projects/[slug]/view-repo.tsx, apps/admin/src/app/projects/[slug]/view-trends.tsx, apps/admin/src/app/projects/actions.tsx, apps/admin/src/app/projects/page.tsx, apps/admin/src/components/add-project-to-repo-button.tsx, apps/admin/src/components/project-table.tsx, packages/db/drizzle/0002_minor_sentry.sql, packages/db/drizzle/meta/0002_snapshot.json, packages/db/drizzle/meta/_journal.json, packages/db/src/projects/create.ts, packages/db/src/projects/find.ts, packages/db/src/projects/get.ts, packages/db/src/schema.ts
One of the goals of the migration to Postgres was to allow multiple projects to be linked to the same repository, which is a common pattern with the raise of monorepos.
This is why the database design includes 2 separate tables:
- `repos`: only includes the data from GitHub about a given repository
- `projects`: connected to repos via the `repoId`, have their own name, description, URL, tags
From the schema.ts file:
```ts
export const projects = pgTable("projects", {
id: text("id").primaryKey(),
name: text("name").notNull().unique(),
slug: text("slug").notNull().unique(),
description: text("description").notNull(),
repoId: text("repoId")
.references(() => repos.id, { onDelete: "cascade" })
.notNull(),
});
export const repos = pgTable("repos", {
id: text("id").primaryKey(),
archived: …
```
=> Feat(admin) Allow multiple projects linked to a single repository

apps/admin/src/app/projects/[slug]/edit/project-form.tsx, apps/admin/src/components/project-table.tsx, apps/backend/src/tasks/build-static-api.task.ts, packages/db/src/constants.ts, packages/db/src/schema.ts
- setup the list of available project statuses in a constant to keep the code DRY
- don't process `deprecated` or `hidden` projects  when building the static API
Also included: make `slug` field editable in project form.
From the admin panel, ensure the statuses show up properly when editing an existing project
=> Improve project statuses

apps/backend/src/iteration-helpers/project-processor.ts, apps/backend/src/iteration-helpers/repo-processor.ts
SQL queries made with `limit 0` return no rows but we used to use `0` as the default value because Drizzle was ignoring `limit` if it was zero... until the following issue was handled:
https://github.com/drizzle-team/drizzle-orm/issues/2011
Yesterday the upgrade to the latest version of Drizzle (#310 ) broke the build process of the app.
=> Fix db queries limit parameter, don't pass `0`

.github/tooling/github-actions/install/action.yml, .github/workflows/pull-request-check.yml
- Instead of waiting for the deploy on Vercel to run the E2E tests, run the test in local after building the application, to make the check faster
- Only run E2E tests when PR are merged (to be revisted when migrating to Turbo monorepo maybe)
Cache for Next.js build: https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#github-actions
=> Run E2E tests against localhost instead of Vercel Preview URL

apps/backend/src/tasks/build-static-api.task.ts, apps/bestofjs-nextjs/package.json, apps/bestofjs-nextjs/src/app/hall-of-fame/hall-of-member-list.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-npm/dependencies-section.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-header.tsx, apps/bestofjs-nextjs/src/components/core/project-logo.tsx, apps/bestofjs-nextjs/src/components/core/project-utils.ts, apps/bestofjs-nextjs/src/components/project-list/project-table.tsx, apps/bestofjs-nextjs/src/lib/global.d.ts, apps/bestofjs-nextjs/src/server/api-utils.tsx, apps/bestofjs-webui/package.json, apps/bestofjs-webui/src/components/core/project-avatar.tsx, apps/bestofjs-webui/src/components/home/home.tsx, apps/bestofjs-webui/src/components/project-list/project-table.tsx, apps/bestofjs-webui/src/containers/project-data-container.ts, apps/bestofjs-webui/src/global.d.ts, packages/db/src/projects/project-helpers.ts
A small change about the JSON file used as the "static" API to make it closer to the underlying data, as a preparations step to eventually remove the static API and query the DB directly.
- `icon` => `logo`
I noticed the mismatch when working on migration of Hall of Fame data.
=> Rename `icon` => `logo` in static JSON API

apps/backend/src/iteration-helpers/repo-processor.ts, apps/backend/src/tasks/build-monthly-rankings.ts, apps/backend/src/tasks/build-static-api.task.ts, apps/backend/src/tasks/hello-world.task.ts, apps/backend/src/utils.ts, apps/bestofjs-nextjs/src/server/api-rankings.ts, packages/db/drizzle/0004_overjoyed_aqueduct.sql, packages/db/drizzle/meta/0004_snapshot.json, packages/db/drizzle/meta/_journal.json, packages/db/package.json, packages/db/src/projects/project-helpers.ts, packages/db/src/schema.ts, packages/db/src/snapshots/monthly-trends.ts
- Remove duplicate projects in the Monthly Rankings JSON file generated every month. Because of #308 several projects from the same repo can show up, E.g. `Svelte Flow` and `React Flow`. It should fix the error about duplicate keys when displaying the list.
- Truncate description in the JSON file (the description is not used anyway)
- In generated data, handle number of stars at the end of the month instead of at the time the script is launched: to be able to re-run the script for a given month without triggering changes about `stars`
- introduce a `priority` field in the project schema to be able to set priorities for projects belonging to the same repo
To generate the rankings from September
```sh
bun run apps/backend/src/cli.ts build-monthly-rankings --year 2024 --month 9
```
The files …
=> Various fixes about monthly rankings generation

apps/admin/package.json, apps/admin/src/app/projects/[slug]/actions.ts, apps/bestofjs-nextjs/next-env.d.ts, apps/bestofjs-nextjs/next.config.mjs, apps/bestofjs-nextjs/package.json, pnpm-lock.yaml
I have found an issue in production while working on the query string parameters:
- Open a new browser tag and go directly to a tag URL such as: https://bestofjs.org/projects?tags=react 
- Go to the Projects page from the navigation menu: the URL changes to `/projects` (the query string is removed) but nothing happens on the screen
It seems related to the experimental feature [ppr](https://nextjs.org/docs/app/api-reference/next-config-js/ppr) that was setup to speed up the project details page that contains dynamic features. I'm not sure we need this feature anyway, so this PR upgrades to the latest **stable** version of Next.js (`14.2.14`, no more "canary*") and removes the ppr feature
Ensure the bug described above does not happen anymore.
=> Upgade to latest stable Next.js 14.2.4

.github/workflows/pull-request-check.yml, apps/backend/package.json, apps/backend/src/iteration-helpers/hall-of-fame-processor.ts, apps/backend/src/iteration-helpers/project-processor.ts, apps/backend/src/iteration-helpers/repo-processor.ts, apps/backend/src/tasks/update-github-data.task.ts, apps/backend/src/tasks/update-hall-of-fame.ts, apps/backend/src/tasks/update-package-data.task.ts, packages/db/package.json, packages/db/src/drizzle.ts, pnpm-lock.yaml
After the migration to Drizzle 0.35 #326, I noticed lots of TS errors (73 errors!) in the `backend` app.
I'm not sure about the exact cause, but it seems that removing `drizzle-orm` from `backend` app and re-exporting drizzle-orm from the `db` package fixes the issue.
```sh
pnpm -F backend typecheck
```
The type checking task should run in all packages on GitHub actions, after every push to ensure we don't miss these errors.
=> Remove "drizzle-orm" package from backend app

packages/db/package.json, packages/db/src/schema.ts, pnpm-lock.yaml
- Upgrade to latest version of Drizzle Kit
- Fix deprecation warning about `pgTable`: using the array syntax instead of the object syntax for the extra argument that specifies the indexes)
```
pnpm -F db studio
```
=> Chore(db) Upgrade Drizzle Kit

apps/admin/src/app/projects/[slug]/view-repo.tsx, apps/bestofjs-nextjs/src/app/projects/[slug]/project-details-github/github-card.tsx
Improve the UI about GitHub data in project details page:
- show the `last_commit` date instead of `pushed_at` (because pushed_at is not really relevant, what we want to show is the last commit on the default branch)
- make the layout more responsive
Visit the project details page, notice the layout swtiches between 1 column and 2 columns depending on the screen size.
=> Show `last_commit` instead of `pushed_at` in GitHub card

.gitignore, apps/backend/package.json, apps/backend/src/backup/README.md, apps/backend/src/backup/make-backup.ts, package.json, pnpm-lock.yaml
Script to be run manually to generate a backup file of the Postgres database in the folder `db-backup`, at the root of the monorepo.
Requirement: `pg_dump` (should come with `psql`)
Added to `package.json` for convenience:
```sh
bun run backup
```
For production database:
```sh
NODE_ENV=production bun run ./apps/backend/src/backup/make-backup.ts
```
=> Add database backup script

.github/workflows/pull-request-check.yml, .gitignore, package.json, pnpm-lock.yaml, turbo.json
After some exploration (https://github.com/bestofjs/bestofjs/pull/311/) it's time to take advantage of [Turbo](https://turbo.build/docs/core-concepts/remote-caching) to orchestrate 🎶  all scripts within the repo!
Benefits:
- Provide global commands to ensure the code is "clean" running type checking and linting against all workspaces
- Speed up commands in local (avoiding useless operations if nothing changed)
- Provide better control about what to trigger when anything changes (compared to what is available on GitHub Actions) and the ability to run the checks in local
To run the type checking command against **all** workspaces within the repo:
```sh
pnpm run typecheck
```
I wanted to skip the Turbo commands against the `legacy` app that triggers hundreds of TS errors, this why I set up …
=> Introduce Turbo to orchestrate monorepo scripts

apps/web/scripts/build-project-data.mjs
After the latest changes, it seems there is a caching issue when calling the pre-build script that fetches data from the JSON file deployed by `bestofjs-static-api-v2` on Vercel.
From the log on Vercel, for `bestofjs` project:
```
web:build: === Build JSON files for the backend... ===
web:build: Fetching data from https://bestofjs-static-api-v2.vercel.app/projects.json
web:build: Fetched data 2025-04-19T22:15:05.275Z
web:build: Copy /vercel/path0/apps/web/public/data/projects.json
web:build: === Prebuild process OK! ===
```
It should fetch data for `2025-04-20T21:54:52.876Z` instead (the date inside the latest JSON file generated this morning)
Tricky to test as we need to merge and wait 24 hours and check the build logs!
=> Try to fix caching issue with JSON data

.github/workflows/pull-request-check.yml, .github/workflows/update-bundle-size.yml, .github/workflows/update-github-data.yml, .github/workflows/update-package-data.yml, .npmrc
Fix the broken scripts running on GitHub Actions after the introduction of PNPM 10 Catalog feature: #356 
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'debug' 
```
It seems we need to add a suffix `...` when running `pnpm -F backend install` commands!
Trigger actions manually from GitHub Actions tab
- Update GitHub data
- Update Package date
- Update Package Size
=> Fix GitHub Actions after migration to PNPM catalog feature

apps/backend/src/tasks/build-static-api.task.ts
Cleanup related to the generatation of the "static API" (JSON file consumed by the web app, used when performing search and displaying lists of projects)
Build the static API in local:
```
bun run apps/backend/src/cli.ts build-static-api
```
Ensure projects are filtered correctly.
```
ℹ Finding ids of projects to process...                                                                                       2:39:28 PM
◐ Processing 3120 project(s)...                                                                                                2:39:28 PM
ℹ Processed 3120 project(s) in 12.2s (Avg: 4ms)                                                                               2:39:41 PM
ℹ 2493 projects to include in the main JSON file { trendingToday: …
```
=> Refactor main list filter function

apps/backend/src/tasks/build-static-api.task.ts
Fix a miss after the refactor in #360 : newly created projects should not be included. We need at least 2 days of data to show the daily trend.
=> Fix static API build process after refactoring

apps/web/src/app/api/og/og-image-layout.tsx, apps/web/src/app/api/og/og-utils.tsx
Fix #366 I should have not added `<title>` attributes to SVG files used to generate dynamic OG images, to satisfy one of the linting rules provided by Biome (we migrated 3 weeks ago: #364 )
Visit `/api/og` and ensure the OG image is rendered correctly
=> Fix OG images removing the `<title>` attribute from SVG files

apps/web/next-env.d.ts, docker-compose.yaml, package.json, packages/db/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
- Upgrade Next.js (`15.5.2`) and Drizzle packages to latest version
- Freeze local Postgres running with Docker to avoid compatibility issues
- Cleanup PNPM catalog running `pnpm update`
- Add  `pnpm -F db push` command: https://orm.drizzle.team/docs/drizzle-kit-push
=> Upgrade Drizzle and Next.js to latest

apps/backend/package.json, apps/backend/src/apis/npm-api-client.ts, apps/web/src/app/projects/project-search-state.ts, apps/web/src/app/tags/tag-search-state.ts, apps/web/src/lib/page-search-state.ts, package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Upgrade from Zod 3 to Zod 4 and cleanup dependencies, running `pnpm dedupe` command
Migration guide: https://zod.dev/v4/changelog
Changes:
- `z.record(z.string(), z.string())` for  package.json dependencies
- `z.ZodType` for any Zod schema (and some TS gymnastic to satisfy the compiler in `page-search-state.ts`)
=> Upgrade to Zod 4 and `dedupe` dependencies
